spring:
  datasource:
    url: jdbc:mysql://192.168.31.110:3306/userWallet?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:*/mapper/*.xml  #指定sql映射文件
  type-aliases-package: com.seaton.wallet.entity
  global-config:
    db-config:
      id-type: auto